http:
  host: "![oOGU+PcG9r3pxuH0PCVWHg==]"
  port: "![9SVIQnipjIM=]"

process:
  host: "![yA91UYn2hJ1+e0/ayRWH3iZ5Dj3vWnKsB/crK8UA93GnQts6louHGDY8RuF4mWfu]"
  port: "![xg/bqwQr3Uk=]"
  basepath: "![fGYXgXZvIu0=]"

api:
  autodiscovery: "![7y15eElYObvtcM402bu4JQ==]"

